name: xkcd_clock
description: A Flutter implementation of the xkcd clock.
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/face.png
  fonts:
    - family: xkcd script
      fonts:
        - asset: assets/xkcd-script.ttf
